#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
__title__ = ''
__author__ = 'xuepl'
__mtime__ = '2019/7/24'
# code is far away from bugs with the god animal protecting
    I love animals. They taste delicious.
..........................................................................................
.......................................................................,]/@@@@@...........
..................................................................,]@O@@@@@@@/............
................................................@@OOOOOOO@@O\]]/Ooooo@@@@@@@`.............
................................................=OOOOooooooO@oooooooO@@@@@`...............
.................................................@OOOOOO@@oooooooooo@@@@ooo@\]............
..........]]]]]]]]]]]]`...........]]/OOO\]]]`..../OOO@@ooooooooooooo@OooooooooooO\`.......
.,/@@@@@@@ooooooooooooooooooOO@OooooooooooooooooOO@@@oooooooooooo@OooooooooooooooooOO\....
\@@@@@@@@@@ooooooooooooooooooooooooooooooooooooooooooooooooooO@OoooooooooooooooooooooooO\.
.....[@@@@@@OooooooooooooooooooooooooooooooooooooooooooOOO@@OOOOOOooooooooooooooooooooooO`
...........[[[[[@@@OOOOOOOooooooooooooooooooooooooooooooO@OOOOOOOOOOooooooooooooooooooo/..
.............]/@`.......\ooo@@^..ooooooooooooooooO@@Ooooo@OOOOOOOOOOOOoooooooooooooooO`...
............/@oooo@`...=/ooO@@@@@Ooooooooooooooo\..=@@ooo@OOOOOOOOOOOOOooooooooooooo/.....
...........,OooooooO\..@oooo@@@@oooooooooOoooooo/@@@@@ooo@@@OOOOOOOOOOOOOoooooooooO`......
............Oooooooooo@OooooooooooooooooOooooooooo@@@oooo@@^.[@@OOOOOOOOOOooooooo/........
............=\oooooooO@@@@@@OooooOooooO@@OoooooooooooooooO@@`....[@@OOOOOOOOoooO^.........
.............@ooooooo@@@@@@@@ooooo@@@@@@@@@@@@@@ooooO@@@@O@O@`.......,\@@OOOOo/...........
.............=oooooooO@@@@@@@oooooo@@@@@@@@@@@ooooo@@@@@@@@@O@............[@@^............
.............=@ooooooo@@@@@@OooooooO@@@@@@@@@oooooo@@@@@@@@@OO\...........................
..............\oooooooo@ooooooooooooO@@@@@@Oooooooo@@@@@@@@OOO@`..........................
...............@ooooooooOOooooooooooo\@@@@ooooooooooo@@@@ooO@]`...........................
...............,@OooooooooOOooooooooooooooooooooooooooOOoooooooo@`........................
................=@OoooooooooO@oooooooooooooooooooooO@OoooooooooooooO\.....................
.................=@OOooooooooooooooooooooooooooooOooooooooooooooooooooo@^.................
...................@OOOooooooooooooooOOOOooooooooooooooooooooooooooooooo@`................
....................=@OooooooooooooooooOOOooooooooooooooOOOoooooooooooo@[.................
..................../ooooooooooooooooooooooooooooooooooo@@@@@OO@@O[[[[O...................
...................,Oooooooooooooooooooooooooooooooooooo@@@@@^............................
...................=Ooooooooooooooooooooooooooooooooooooo@@@`.............................
...................Oooooooooooooooooooooooooooooooooooooo@/...............................
..................,@oooooooooooooooooooooooooooooooooooooo^...............................
..................=ooooooooooooooooooooooooooooooooooooooo\...............................
`.................@oooooooooooooooooooooooooooooooooooooooO`..............................
`................=ooooooooooooooooooooooooooooooooooooooooo^..............................
.................=oooooooooooooooooooooooooooooooooooooooooO..............................
.................OoooooooooooooooooooooooooooooooooooooooooO^.............................
.................=oooooooooooooooooooooooooooooooooooooooooo^.............................
`................,OOoooooooooooooooooOOOOOOOoooooooooooooooo^. ...........................
........        ..,@OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@/..         ...................
.......           ..\@OOOOOOO@OO@@@@@@@OOOO@@@@@@@OOOOOOO@O`..           .................
........        ..,@OO@OO@@[....                 ...[@OOo/o@@`..         .................
..........      ./O@@O[`....                        ....[[@@@O\.       ...................
.............   .......                                  .......   .......................
..................                                           .............................
..........................................................................................
"""